title: Samrat K S
description: General | Golang | Database
url: "https://samratkashipathi.github.io"
baseurl: ""

remote_theme: riggraz/no-style-please

# Visual Settings
google_analytics: # Add ID here if you have one

# Plugins required for GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# Author Details (Appears in SEO tags)
author:
  name: Samrat K S

# Exclude standard junk files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor