title: Samrat K S
description: General | Golang | Database
url: "https://samratkashipathi.github.io"
baseurl: "/samrat.github.io"

remote_theme: riggraz/no-style-please

# Theme Configuration
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

# Visual Settings
google_analytics: # Add ID here if you have one

# Plugins required for GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# Author Details (Appears in SEO tags)
author:
  name: Samrat K S

# Exclude standard junk files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor